name: Convert Notebooks to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install jupyterthemes jupyter
          jt -t onedork

      - name: Convert notebooks to HTML
        run: |
          for notebook in $(ls *.ipynb); do
            jupyter nbconvert --to html --template full "$notebook"
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.html
          git commit -m "Convert notebooks to HTML with dark theme"
          git push
